title: Pranav Vishnoi

author:
  name: Pranav Vishnoi
  email: pranav.vishnoi.dev@gmail.com

baseurl: "https://0xprv.github.io/" 
url: "https://0xprv.github.io/"

theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag

sass:
  quiet_deps: true
  silence_deprecations: [import]

minima:
  skin: dark

  nav_pages:
    - about.md

  show_excerpts: true

  social_links:
    - title: GitHub
      icon: github
      url: "https://github.com/0xprv"

    - title: X (Twitter)
      icon: x-twitter
      url: "https://x.com/0xprv"

    - title: LinkedIn
      icon: linkedin
      url: "https://linkedin.com/in/pranavvishnoi"
