# Site-wide settings
# ------------------
#
title: Your awesome title
#
author:
    name: GitHub User
    email: your-email@domain.com

theme: minima
remote_theme: jekyll/minima@d4d779a
plugins:
  - jekyll-feed
  - jekyll-seo-tag

